### PR TITLE
Jacobs changes

### PR DESCRIPTION
**Pull request by smartercleanup**
cleaning up the front end a little

### CODE REVIEW

**Comment by LukeSwart** [comment]
Thanks for the changes! My only concern is that you enabled geolocation on load. Do you think this would be confusing if someone was testing our app from outside the region? What if they were outside the bounding box? Perhaps we can add a check that would geolocate them on load only if they were within a specific area...

**Comment by LukeSwart** [comment]
Also, I'm not sure if you got my IRC message, but we can change the title of 'Recent Report Activity' to 'Activity Stream' in `src/sa_web/templates/base.html`. There's an issue to get this into our config, although I was hoping Andy would help us with that issue.

**Comment by smartercleanup** [comment]
I hear your concerns in regards to enabling geolocation on load. My main reason for doing this is to make it as easy as possible for mobile phone users. I think many users will neglect to hit the little target icon in order to turn it on geolocation, and without it, the app is not very useful on a phone.

Geolocation based on specific area would be great if that's possible, or do we have to code it?

**Comment by LukeSwart** [comment]
That makes sense. And yes, the geolocation would be another ticket. I'll merge this now and we'll file another ticket for the geolocation.

**Pull request merged**
